# Generated by Django 3.2.5 on 2022-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, default='None', max_length=10),
        ),
    ]
