# Generated by Django 3.2.5 on 2022-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_generaltaskmodel_personaltaskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='members',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='chats',
            field=models.ManyToManyField(related_name='messages', to='crm.Chat'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='priority',
            field=models.CharField(default='LOW', max_length=25),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
