# Generated by Django 3.2.5 on 2022-04-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20220430_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
